apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "todo"
            - name: POSTGRES_DB
              value: "todo"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "todo", "-d", "todo"]
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc
